### PR TITLE
Optionally update grub when we do activate and renames on BEs

### PR DESCRIPTION
**Pull request by kmoore134**
This allows "beadm activate" to be used to set the next BE to boot
automatically when using sysutils/grub2-pcbsd

### CODE REVIEW

**Comment by kmoore134** [comment]
This has various changes, but primarily it includes support for "nicknames" as dataset properties, and adds the export / import commands, for dumping a BE to a file and loading it elsewhere.

**Comment by vermaden** [comment]
What is the difference between BENAME and NICKNAME?

**Comment by kmoore134** [comment]
BENAME is the dataset as in: <pool>/ROOT/<BENAME>
NICKNAME is the ZFS property set on the dataset

So, this adds a extra field at the end of 'beadm list', the nickname. It is a ZFS property which can be changed on the fly, without changing the underlying dataset. I.E. in the case the dataset is currently mounted to /. This is being used in FreeNAS so they can relabel BE's dynamically, like "default" "previous", etc, with the real dataset still being some auto-generated name like "be-auto-<timestamp>". Plus it allows them to use white-space in the nicknames, something beadm doesn't do with datasets properly. 

Additional some commands allow using the -n <nickname> flag now. In this case, the nickname will be converted to the dataset name, before doing the operation.

**Comment by vermaden** [comment]
Thanks for explanation.

Seems that Your 'fork' of beadm has grown so much that it is now 'the' beadm for FreeBSD :)

You may also think about merging the bootpool version as FreeBSD loader does not support booting from ZFS on top of GELI without another /boot partition or ZFS pool, from here:
https://bitbucket.org/aasoft/beadm/src/d0efcdfc5f05cb84d8b319a0f31d7e09f56eb295/beadm

Regards,
vermaden

**Comment by kmoore134** [comment]
I wasn't so wild on adding the bootpool option to beadm, especially since proper GELI support is about to land for 11.0, which makes the bootpool unnecessary. 

https://reviews.freebsd.org/D4593

Glad our "fork" is improving, I'll be happy to keep sending you changes as we roll them. So far nothing else is on the radar, but we shall see ;)

**Comment by bdrewery** [comment]
For FreeBSD I've always wanted to keep beadm closer to the OpenSolaris version so we could eventually import it directly into base, and not need the port anymore.  Also I wanted to keep the interface the same since it is an established tool.  These commits add a lot of new functionality that is not documented well and lacks a justification.  Nicknames seem to be ambiguous in a few cases, and I don't see the point for them, when a user could easily set their own property on a dataset.  Likewise for rename, there's no reason beadm needs to wrap `zfs rename`.  The commit logs being full of 'fix bugs' does not give me confidence or tell me what bugs were fixed.  I'm inclined to not commit any of this into the FreeBSD port.

**Comment by kmoore134** [comment]
I really don't have a problem with that. The nickname thing was a "FreeNAS-ism" that I wasn't particularly fond-of in the first place ;)

And yes, the sooner you get a version into base the better. Hard to say FreeBSD supports BE's when you still have to install a port to interact with them.

**Pull request merged**
